services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy # https://github.com/nginx-proxy/nginx-proxy
    ports:
      - "8083:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "200M"
    ports:
      - "7942:80"
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=172.17.0.1,localhost,127.0.0.1
      - VIRTUAL_PORT=80
    volumes:
      - ./main.py:/code/main.py