services:
  # 로드 밸런서 lb
  lb:
    # Docker Hub에서 다운 받을 이미지
    image: nginxproxy/nginx-proxy # https://github.com/nginx-proxy/nginx-proxy
    # 포트
    ports:
      - "8949:80"
    # 저장 위치
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - api
  
  cache:
    image: nginx
    ports:
      - "8083:80"
    volumes:
      - ./conf/cache/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - lb
    deploy:
      resources:
        limits:
          cpus: "1.05"
          memory: "400M"

  api:
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "200M"
    ports:
      - "7942:80"
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=172.17.0.1,localhost,127.0.0.1
      - VIRTUAL_PORT=80
    volumes:
      - ./main.py:/code/main.py