services:
  web1:
    image: httpd:latest
    volumes:
      - ./pyweb1:/usr/local/apache2/htdocs
    deploy:
      resources:
        limits:
          cpus: "0.01" 
          memory: "40M"
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=MacBook-Pro.local
      - VIRTUAL_PORT=80
  
  nginx-proxy:
    image: nginxproxy/nginx-proxy # https://github.com/nginx-proxy/nginx-proxy
    ports:
      - "8083:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web1
