services:
  web1:
    image: httpd:latest
    ports:
      - "8081:80"
    volumes:
      - ./pyweb1:/usr/local/apache2/htdocs
    deploy:
      resources:
        limits:
          cpus: "0.01" 
          memory: "50M"

  web2:
    image: httpd:latest
    ports:
      - "8082:80"
    volumes:
      - ./pyweb2:/usr/local/apache2/htdocs
    deploy:
      resources:
        limits:
          cpus: "0.01"
          memory: "50M"

  lb:
    image: nginx
    ports:
      - "8083:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web1
      - web2
    deploy:
      resources:
        limits:
          cpus: "0.05"     # 최대 5% CPU 사용
          memory: "20M"  # 최대 20MB 메모리 사용
